steps:
- id: 'Docker end-to-end test'
  name: gcr.io/cloud-builders/docker
  args: ['./test/docker_e2e.sh']
- id: 'Lint: Formatting'
  name: golangci/golangci-lint:v1.23.8
  # Disable staticcheck since grpc-gateway doesn't use DialContext
  args: ['golangci-lint', 'run', '--timeout', '5m', '-v', '-E', 'gofmt,bodyclose,rowserrcheck,misspell,golint', '-D', 'staticcheck,vet']
  volumes:
  - name: 'go-vol'
    path: '/go'
- id: 'Lint: Formatting: vet'
  name: golangci/golangci-lint:v1.23.8
  # Run vet separately to try and fix https://github.com/golangci/golangci-lint/issues/896
  args: ['golangci-lint', 'run', '-v', '--disable-all',  '-E', 'vet', '--timeout', '5m']
  volumes:
  - name: 'go-vol'
    path: '/go'
- id: 'Lint: Formatting staticcheck'
  name: golangci/golangci-lint:v1.24.0
  # Run staticcheck everywhere but the http-gateway
  args: ['golangci-lint', 'run', '-v', '--disable-all',  '-E', 'staticcheck', '--skip-dirs', '^cmds/http-gateway,^pkg/logging', '--timeout', '5m']
  volumes:
  - name: 'go-vol'
    path: '/go'
- id: 'Test: 10x with Race Detection and Coverage'
  name: golang
  env: ['GO111MODULE=on']
  args: ['go', 'test', './...', '-race', '-test.count', '10', '-cover']
- id: 'Evaluate examples/minimum'
  name: 'grafana/tanka'
  args:
  - 'show'
  - '--dangerous-allow-redirect'
  - 'build/deploy/examples/minimum'
- id: 'Evaluate examples/prod'
  name: 'grafana/tanka'
  args:
  - 'show'
  - '--dangerous-allow-redirect'
  - 'build/deploy/examples/prod'
- id: 'Evaluate examples/schema_manager'
  name: 'grafana/tanka'
  args:
  - 'show'
  - '--dangerous-allow-redirect'
  - 'build/deploy/examples/schema_manager'
